services:
  scheduler:
    volumes:
      - /Users/de_learn/Documents/portfolio/sales-pipeline-analytics/simulator:/usr/local/airflow/include/simulator:ro
      - /Users/de_learn/Documents/portfolio/sales-pipeline-analytics/dbt_pipeline:/usr/local/airflow/include/dbt_pipeline